repos:
  # Python backend hooks
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-django==1.3.0]

  # JavaScript/React frontend hooks
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        # Target only your source files
        files: ^frontend/src/.*\.(js|jsx|css|scss|json)$
        # Explicitly exclude node_modules
        exclude: node_modules
        # Narrower type specification
        types: [ javascript, css, scss, json ]
        additional_dependencies:
          - prettier@3.1.0


  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0'
    hooks:
      - id: eslint
        files: \.(js|jsx)$
        exclude: node_modules
        additional_dependencies:
          - eslint@8.56.0
          - eslint-plugin-react@7.33.2

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: node_modules/.*
